// fail-closed 围栏:omp 唯一能在执行前拦 bash 的层。
//
// 职责(与既有机制互补,不重复):
//   1. 破坏性 bash 分档:never-legit 硬 block;usually-fine 有 UI 时 confirm、无 UI 时放行 + 告警。
//   2. 写生成代码:按【路径】拦 write/edit/apply_patch/bash 落到 gen 目录。
//      补 edit.blockAutoGenerated(默认开,但只管 edit 工具 + 标准 banner)的三缺口:
//        - write 全量覆盖
//        - bash 重定向 / sed -i 改 gen 路径
//        - 非标准 banner 文件(routeTree.gen.ts:banner 是 "TanStack Router"+@ts-nocheck,非 @generated)
//
// 声明:破坏性 bash 拦截是【防手滑安全网,非对抗沙箱】——`rm -r -f`、变量展开、别名可绕过。
// 不对称:这是 omp-only 臂;理想应进 tools/arch-guard 共享层覆盖所有工具(见 tools/arch-guard/README.md)。
//
// 纯判定函数(classifyBash / isGeneratedPath / extractPatchPaths)导出供 guard.test.ts 单测。

import type { HookAPI } from "@oh-my-pi/pi-coding-agent/extensibility/hooks";

// ── 生成代码路径(分隔符无关:统一转 /,去开头 ./)──────────────────────────
const GENERATED_PREFIXES = [
  "gen/", // proto Go 生成
  "internal/query/", // GORM CLI 生成
  "web/src/gen/", // proto TS 生成
];
const GENERATED_EXACT = [
  "web/src/routetree.gen.ts", // TanStack Router 生成(非标准 banner,blockAutoGenerated 漏判)
];

export function normPath(p: string): string {
  return String(p ?? "")
    .replace(/\\/g, "/")
    .replace(/^\.\//, "")
    .toLowerCase();
}

export function isGeneratedPath(p: string): boolean {
  const n = normPath(p);
  if (!n) return false;
  if (GENERATED_EXACT.includes(n)) return true;
  return GENERATED_PREFIXES.some((pre) => n.startsWith(pre) || n.includes("/" + pre));
}

// 从 apply_patch 文本提取被写的文件路径(*** Add/Update/Delete File:)。
export function extractPatchPaths(patchText: string): string[] {
  const out: string[] = [];
  const re = /^\*\*\* (?:Add|Update|Delete) File:\s*(.+)$/gm;
  let m: RegExpExecArray | null;
  while ((m = re.exec(String(patchText ?? ""))) !== null) {
    out.push(m[1].trim());
  }
  return out;
}

// ── bash 分档 ────────────────────────────────────────────────────────────
export type BashVerdict =
  | { level: "ok" }
  | { level: "block"; reason: string } // never-legit:硬拦
  | { level: "confirm"; reason: string }; // usually-fine:有 UI 则确认,无 UI 放行 + 告警

// rm -rf 的危险目标 token(去引号后整词匹配):根 / 当前 / 上级 / home / 通配 / 绝对路径。
const RM_DANGER_TARGET = /^(\/|\.|\.\.|~|\$HOME|\*|\/\S*)$/;

// 命令是否含 rm 且带 recursive+force(任意顺序/合并:-rf -fr -Rf -r -f --recursive --force)。
function isRmForce(cmd: string): boolean {
  if (!/\brm\b/.test(cmd)) return false;
  const flags = cmd.match(/(?:^|\s)-[a-zA-Z]+/g) ?? [];
  const letters = flags.join("");
  const recursive = /r/i.test(letters) || /--recursive/.test(cmd);
  const force = /f/.test(letters) || /--force/.test(cmd);
  return recursive && force;
}

// rm -rf 的目标参数(粗解析:取非 flag、非 rm 的 token,去引号)。
function rmTargets(cmd: string): string[] {
  const toks = cmd.split(/\s+/).filter(Boolean);
  const out: string[] = [];
  let seenRm = false;
  for (const t of toks) {
    if (t === "rm") {
      seenRm = true;
      continue;
    }
    if (!seenRm) continue;
    if (t.startsWith("-")) continue;
    out.push(t.replace(/^["']|["']$/g, ""));
  }
  return out;
}

export function classifyBash(command: string): BashVerdict {
  const cmd = String(command ?? "");

  // git push --force / -f(排除 --force-with-lease,它安全)
  if (/\bgit\s+push\b/.test(cmd) && /(--force(?!-with-lease)\b|(?:^|\s)-f\b)/.test(cmd)) {
    return { level: "block", reason: "git push --force 会覆盖远端历史(用 --force-with-lease 更安全)" };
  }

  if (isRmForce(cmd)) {
    const targets = rmTargets(cmd);
    const deadly = targets.some((t) => RM_DANGER_TARGET.test(t));
    if (deadly) {
      return { level: "block", reason: `rm -rf 目标危险(${targets.join(" ")}):根/当前/上级/home/通配/绝对路径` };
    }
    return { level: "confirm", reason: `rm -rf ${targets.join(" ")}:递归强制删除` };
  }

  // git reset --hard:丢弃工作区改动
  if (/\bgit\s+reset\s+--hard\b/.test(cmd)) {
    return { level: "confirm", reason: "git reset --hard 丢弃未提交改动" };
  }

  // 数据库破坏:DROP DATABASE / DROP TABLE / TRUNCATE
  if (/\b(DROP\s+(DATABASE|TABLE)|TRUNCATE(\s+TABLE)?)\b/i.test(cmd)) {
    return { level: "confirm", reason: "SQL DROP/TRUNCATE 不可逆删除数据" };
  }

  return { level: "ok" };
}

// bash 是否把内容写入 gen 路径(重定向 > / >> 、tee、sed -i)。
function bashWritesGenerated(cmd: string): string | null {
  const c = String(cmd ?? "");
  // 重定向目标 / tee 目标 / sed -i 目标:取所有疑似路径 token,逐个判定。
  const toks = c.split(/[\s><|]+/).filter(Boolean);
  for (const t of toks) {
    const p = t.replace(/^["']|["']$/g, "");
    if (isGeneratedPath(p)) return p;
  }
  return null;
}

export default function hook(pi: HookAPI): void {
  pi.on("tool_call", async (event, ctx) => {
    try {
      const tool = event.toolName;
      const input = (event.input ?? {}) as Record<string, unknown>;

      // ── 文件写工具:拦 gen 路径 ──
      if (tool === "write" || tool === "edit") {
        const p = (input.path ?? input.file_path) as string | undefined;
        if (p && isGeneratedPath(p)) {
          return { block: true, reason: `禁止手改生成文件 ${p}:由 codegen 产出,改 proto/model 后跑 task gen 重生成。` };
        }
        return;
      }
      if (tool === "apply_patch") {
        const patch = (input.patch ?? input.input ?? "") as string;
        const hit = extractPatchPaths(patch).find(isGeneratedPath);
        if (hit) {
          return { block: true, reason: `禁止手改生成文件 ${hit}:由 codegen 产出,跑 task gen 重生成。` };
        }
        return;
      }

      // ── bash ──
      if (tool === "bash") {
        const cmd = String(input.command ?? "");

        const genHit = bashWritesGenerated(cmd);
        if (genHit) {
          return { block: true, reason: `命令写入生成文件 ${genHit}:由 codegen 产出,跑 task gen 重生成。` };
        }

        const v = classifyBash(cmd);
        if (v.level === "block") {
          return { block: true, reason: `已拦截危险命令:${v.reason}` };
        }
        if (v.level === "confirm") {
          if (!ctx.hasUI) {
            // 无 UI(子 agent / CI):手滑安全网降级为告警,不阻断。
            ctx.ui.notify?.(`⚠ 放行潜在危险命令(无 UI 无法确认):${v.reason}`);
            return;
          }
          const ok = await ctx.ui.confirm("危险命令确认", `${v.reason}\n\n${cmd}\n\n允许执行?`);
          if (!ok) return { block: true, reason: `用户拒绝执行:${v.reason}` };
        }
      }
    } catch {
      // 判定逻辑异常一律放行(fail-open),避免误杀正常操作;围栏是尽力而为。
      return;
    }
  });
}
