// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var API = struct {
	ID          field.Number[uint64]
	Procedure   field.String
	Service     field.String
	Method      field.String
	Description field.String
	Group       field.String
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field[gorm.DeletedAt]
}{
	ID:          field.Number[uint64]{}.WithColumn("id"),
	Procedure:   field.String{}.WithColumn("procedure"),
	Service:     field.String{}.WithColumn("service"),
	Method:      field.String{}.WithColumn("method"),
	Description: field.String{}.WithColumn("description"),
	Group:       field.String{}.WithColumn("group"),
	CreatedAt:   field.Time{}.WithColumn("created_at"),
	UpdatedAt:   field.Time{}.WithColumn("updated_at"),
	DeletedAt:   field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}
