// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
)

var CaptchaCode = struct {
	ID        field.String
	Answer    field.String
	ExpiresAt field.Time
}{
	ID:        field.String{}.WithColumn("id"),
	Answer:    field.String{}.WithColumn("answer"),
	ExpiresAt: field.Time{}.WithColumn("expires_at"),
}
