// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var Dictionary = struct {
	ID          field.Number[uint64]
	Type        field.String
	Name        field.String
	Description field.String
	Status      field.Bool
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field[gorm.DeletedAt]
}{
	ID:          field.Number[uint64]{}.WithColumn("id"),
	Type:        field.String{}.WithColumn("type"),
	Name:        field.String{}.WithColumn("name"),
	Description: field.String{}.WithColumn("description"),
	Status:      field.Bool{}.WithColumn("status"),
	CreatedAt:   field.Time{}.WithColumn("created_at"),
	UpdatedAt:   field.Time{}.WithColumn("updated_at"),
	DeletedAt:   field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}

var DictionaryItem = struct {
	ID        field.Number[uint64]
	DictID    field.Number[uint64]
	Label     field.String
	Value     field.String
	Sort      field.Number[int]
	Status    field.Bool
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
}{
	ID:        field.Number[uint64]{}.WithColumn("id"),
	DictID:    field.Number[uint64]{}.WithColumn("dict_id"),
	Label:     field.String{}.WithColumn("label"),
	Value:     field.String{}.WithColumn("value"),
	Sort:      field.Number[int]{}.WithColumn("sort"),
	Status:    field.Bool{}.WithColumn("status"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}
