// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var File = struct {
	ID          field.Number[uint64]
	Name        field.String
	Key         field.String
	URL         field.String
	Size        field.Number[int64]
	ContentType field.String
	Visibility  field.String
	UploadedBy  field.Number[uint64]
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field[gorm.DeletedAt]
}{
	ID:          field.Number[uint64]{}.WithColumn("id"),
	Name:        field.String{}.WithColumn("name"),
	Key:         field.String{}.WithColumn("key"),
	URL:         field.String{}.WithColumn("url"),
	Size:        field.Number[int64]{}.WithColumn("size"),
	ContentType: field.String{}.WithColumn("content_type"),
	Visibility:  field.String{}.WithColumn("visibility"),
	UploadedBy:  field.Number[uint64]{}.WithColumn("uploaded_by"),
	CreatedAt:   field.Time{}.WithColumn("created_at"),
	UpdatedAt:   field.Time{}.WithColumn("updated_at"),
	DeletedAt:   field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}
