// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var ScheduledJob = struct {
	ID          field.Number[uint64]
	Name        field.String
	Handler     field.String
	CronExpr    field.String
	Enabled     field.Bool
	Description field.String
	LastRunAt   field.Time
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field[gorm.DeletedAt]
}{
	ID:          field.Number[uint64]{}.WithColumn("id"),
	Name:        field.String{}.WithColumn("name"),
	Handler:     field.String{}.WithColumn("handler"),
	CronExpr:    field.String{}.WithColumn("cron_expr"),
	Enabled:     field.Bool{}.WithColumn("enabled"),
	Description: field.String{}.WithColumn("description"),
	LastRunAt:   field.Time{}.WithColumn("last_run_at"),
	CreatedAt:   field.Time{}.WithColumn("created_at"),
	UpdatedAt:   field.Time{}.WithColumn("updated_at"),
	DeletedAt:   field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}

var JobExecution = struct {
	ID         field.Number[uint64]
	JobID      field.Number[uint64]
	StartedAt  field.Time
	FinishedAt field.Time
	Status     field.String
	Error      field.String
	DurationMS field.Number[int64]
}{
	ID:         field.Number[uint64]{}.WithColumn("id"),
	JobID:      field.Number[uint64]{}.WithColumn("job_id"),
	StartedAt:  field.Time{}.WithColumn("started_at"),
	FinishedAt: field.Time{}.WithColumn("finished_at"),
	Status:     field.String{}.WithColumn("status"),
	Error:      field.String{}.WithColumn("error"),
	DurationMS: field.Number[int64]{}.WithColumn("duration_ms"),
}
