// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
)

var JobLock = struct {
	LockKey    field.String
	Owner      field.String
	AcquiredAt field.Time
	ExpiresAt  field.Time
}{
	LockKey:    field.String{}.WithColumn("lock_key"),
	Owner:      field.String{}.WithColumn("owner"),
	AcquiredAt: field.Time{}.WithColumn("acquired_at"),
	ExpiresAt:  field.Time{}.WithColumn("expires_at"),
}
