// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
)

var OperationLog = struct {
	ID        field.Number[uint64]
	CreatedAt field.Time
	UserID    field.Number[uint64]
	UserEmail field.String
	Procedure field.String
	Method    field.String
	IP        field.String
	UserAgent field.String
	LatencyMS field.Number[int64]
	Status    field.String
	Error     field.String
	Stack     field.String
}{
	ID:        field.Number[uint64]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UserID:    field.Number[uint64]{}.WithColumn("user_id"),
	UserEmail: field.String{}.WithColumn("user_email"),
	Procedure: field.String{}.WithColumn("procedure"),
	Method:    field.String{}.WithColumn("method"),
	IP:        field.String{}.WithColumn("ip"),
	UserAgent: field.String{}.WithColumn("user_agent"),
	LatencyMS: field.Number[int64]{}.WithColumn("latency_ms"),
	Status:    field.String{}.WithColumn("status"),
	Error:     field.String{}.WithColumn("error"),
	Stack:     field.String{}.WithColumn("stack"),
}

var LoginLog = struct {
	ID        field.Number[uint64]
	CreatedAt field.Time
	UserID    field.Number[uint64]
	Email     field.String
	IP        field.String
	UserAgent field.String
	Success   field.Bool
	Error     field.String
}{
	ID:        field.Number[uint64]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UserID:    field.Number[uint64]{}.WithColumn("user_id"),
	Email:     field.String{}.WithColumn("email"),
	IP:        field.String{}.WithColumn("ip"),
	UserAgent: field.String{}.WithColumn("user_agent"),
	Success:   field.Bool{}.WithColumn("success"),
	Error:     field.String{}.WithColumn("error"),
}
