// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
)

var LoginAttempt = struct {
	AttemptKey field.String
	Fails      field.Number[int]
	FirstAt    field.Time
	ExpiresAt  field.Time
}{
	AttemptKey: field.String{}.WithColumn("attempt_key"),
	Fails:      field.Number[int]{}.WithColumn("fails"),
	FirstAt:    field.Time{}.WithColumn("first_at"),
	ExpiresAt:  field.Time{}.WithColumn("expires_at"),
}
