// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var Menu = struct {
	ID        field.Number[uint64]
	ParentID  field.Number[uint64]
	Path      field.String
	Name      field.String
	Component field.String
	Title     field.String
	Icon      field.String
	Sort      field.Number[int]
	Hidden    field.Bool
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
}{
	ID:        field.Number[uint64]{}.WithColumn("id"),
	ParentID:  field.Number[uint64]{}.WithColumn("parent_id"),
	Path:      field.String{}.WithColumn("path"),
	Name:      field.String{}.WithColumn("name"),
	Component: field.String{}.WithColumn("component"),
	Title:     field.String{}.WithColumn("title"),
	Icon:      field.String{}.WithColumn("icon"),
	Sort:      field.Number[int]{}.WithColumn("sort"),
	Hidden:    field.Bool{}.WithColumn("hidden"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}

var MenuButton = struct {
	ID        field.Number[uint64]
	MenuID    field.Number[uint64]
	Code      field.String
	Name      field.String
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
}{
	ID:        field.Number[uint64]{}.WithColumn("id"),
	MenuID:    field.Number[uint64]{}.WithColumn("menu_id"),
	Code:      field.String{}.WithColumn("code"),
	Name:      field.String{}.WithColumn("name"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}

var RoleMenu = struct {
	RoleCode field.String
	MenuID   field.Number[uint64]
}{
	RoleCode: field.String{}.WithColumn("role_code"),
	MenuID:   field.Number[uint64]{}.WithColumn("menu_id"),
}

var RoleButton = struct {
	RoleCode field.String
	ButtonID field.Number[uint64]
}{
	RoleCode: field.String{}.WithColumn("role_code"),
	ButtonID: field.Number[uint64]{}.WithColumn("button_id"),
}
