// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var SysParam = struct {
	ID          field.Number[uint64]
	Key         field.String
	Name        field.String
	Value       field.String
	Description field.String
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field[gorm.DeletedAt]
}{
	ID:          field.Number[uint64]{}.WithColumn("id"),
	Key:         field.String{}.WithColumn("key"),
	Name:        field.String{}.WithColumn("name"),
	Value:       field.String{}.WithColumn("value"),
	Description: field.String{}.WithColumn("description"),
	CreatedAt:   field.Time{}.WithColumn("created_at"),
	UpdatedAt:   field.Time{}.WithColumn("updated_at"),
	DeletedAt:   field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}
