// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
)

var PasswordResetToken = struct {
	ID        field.Number[uint64]
	TokenHash field.String
	UserID    field.Number[uint64]
	ExpiresAt field.Time
	UsedAt    field.Time
	CreatedAt field.Time
}{
	ID:        field.Number[uint64]{}.WithColumn("id"),
	TokenHash: field.String{}.WithColumn("token_hash"),
	UserID:    field.Number[uint64]{}.WithColumn("user_id"),
	ExpiresAt: field.Time{}.WithColumn("expires_at"),
	UsedAt:    field.Time{}.WithColumn("used_at"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
}

var PasswordHistory = struct {
	ID           field.Number[uint64]
	UserID       field.Number[uint64]
	PasswordHash field.String
	CreatedAt    field.Time
}{
	ID:           field.Number[uint64]{}.WithColumn("id"),
	UserID:       field.Number[uint64]{}.WithColumn("user_id"),
	PasswordHash: field.String{}.WithColumn("password_hash"),
	CreatedAt:    field.Time{}.WithColumn("created_at"),
}
