// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
)

var PluginState = struct {
	Name      field.String
	Enabled   field.Bool
	UpdatedAt field.Time
}{
	Name:      field.String{}.WithColumn("name"),
	Enabled:   field.Bool{}.WithColumn("enabled"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
}
