// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/cli/gorm/typed"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func Query[T any](db *gorm.DB, opts ...clause.Expression) _QueryInterface[T] {
	return _QueryImpl[T]{
		Interface: typed.G[T](db, opts...),
	}
}

type _QueryInterface[T any] interface {
	typed.Interface[T]
	SearchByName(ctx context.Context, keyword string) ([]T, error)
}

type _QueryImpl[T any] struct {
	typed.Interface[T]
}

func (e _QueryImpl[T]) SearchByName(ctx context.Context, keyword string) ([]T, error) {
	var sb strings.Builder
	_params := make([]any, 0, 2)

	sb.WriteString("SELECT * FROM ? WHERE name LIKE ? AND deleted_at IS NULL")
	_params = append(_params, clause.Table{Name: clause.CurrentTable}, keyword)

	var result []T
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}
