// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var Role = struct {
	ID          field.Number[uint64]
	Code        field.String
	Name        field.String
	Description field.String
	Builtin     field.Bool
	Sort        field.Number[int]
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field[gorm.DeletedAt]
}{
	ID:          field.Number[uint64]{}.WithColumn("id"),
	Code:        field.String{}.WithColumn("code"),
	Name:        field.String{}.WithColumn("name"),
	Description: field.String{}.WithColumn("description"),
	Builtin:     field.Bool{}.WithColumn("builtin"),
	Sort:        field.Number[int]{}.WithColumn("sort"),
	CreatedAt:   field.Time{}.WithColumn("created_at"),
	UpdatedAt:   field.Time{}.WithColumn("updated_at"),
	DeletedAt:   field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}
