// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
)

var UserSession = struct {
	ID         field.String
	UserID     field.Number[uint64]
	IP         field.String
	UserAgent  field.String
	CreatedAt  field.Time
	LastSeenAt field.Time
	ExpiresAt  field.Time
}{
	ID:         field.String{}.WithColumn("id"),
	UserID:     field.Number[uint64]{}.WithColumn("user_id"),
	IP:         field.String{}.WithColumn("ip"),
	UserAgent:  field.String{}.WithColumn("user_agent"),
	CreatedAt:  field.Time{}.WithColumn("created_at"),
	LastSeenAt: field.Time{}.WithColumn("last_seen_at"),
	ExpiresAt:  field.Time{}.WithColumn("expires_at"),
}
