// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
)

var UserTOTP = struct {
	UserID      field.Number[uint64]
	Secret      field.String
	Enabled     field.Bool
	ConfirmedAt field.Time
	CreatedAt   field.Time
	UpdatedAt   field.Time
}{
	UserID:      field.Number[uint64]{}.WithColumn("user_id"),
	Secret:      field.String{}.WithColumn("secret"),
	Enabled:     field.Bool{}.WithColumn("enabled"),
	ConfirmedAt: field.Time{}.WithColumn("confirmed_at"),
	CreatedAt:   field.Time{}.WithColumn("created_at"),
	UpdatedAt:   field.Time{}.WithColumn("updated_at"),
}

var TOTPRecoveryCode = struct {
	ID       field.Number[uint64]
	UserID   field.Number[uint64]
	CodeHash field.String
	UsedAt   field.Time
}{
	ID:       field.Number[uint64]{}.WithColumn("id"),
	UserID:   field.Number[uint64]{}.WithColumn("user_id"),
	CodeHash: field.String{}.WithColumn("code_hash"),
	UsedAt:   field.Time{}.WithColumn("used_at"),
}
