// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var User = struct {
	ID           field.Number[uint64]
	Email        field.String
	Name         field.String
	PasswordHash field.String
	Role         field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field[gorm.DeletedAt]
}{
	ID:           field.Number[uint64]{}.WithColumn("id"),
	Email:        field.String{}.WithColumn("email"),
	Name:         field.String{}.WithColumn("name"),
	PasswordHash: field.String{}.WithColumn("password_hash"),
	Role:         field.String{}.WithColumn("role"),
	CreatedAt:    field.Time{}.WithColumn("created_at"),
	UpdatedAt:    field.Time{}.WithColumn("updated_at"),
	DeletedAt:    field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}
