// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
)

var UserRole = struct {
	UserID   field.Number[uint64]
	RoleCode field.String
}{
	UserID:   field.Number[uint64]{}.WithColumn("user_id"),
	RoleCode: field.String{}.WithColumn("role_code"),
}
